version: '3'

services:
  db_wr2net:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db_wr2net
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - wr2_network

  app_wr2net:
    build:
      context: node
    container_name: app_wr2net
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - wr2_network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db_wr2net

  nginx_wr2net:
    build:
        context: ./nginx
        dockerfile: Dockerfile.prod
    image: wr2net/nginx:latest
    container_name: nginx_wr2net
    networks:
      - wr2_network
    ports:
      - "8080:80"

networks:
  wr2_network:
    driver: bridge