version: '3'

services:
  app:
    build:
      context: node
    container_name: app
    volumes:
      - ./node:/usr/src/app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: bash -c "npm install && node index.js"
    networks:
      - wr2_network
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - wr2_network
  nginx:
    build:
      context: nginx
    image: nginx
    container_name: nginx
    networks:
      - wr2_network
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/node.template
    command: 'bash -c "cat /etc/nginx/conf.d/node.template > /etc/nginx/conf.d/default.conf && nginx -g ''daemon off;''"'

networks:
  wr2_network:
    driver: bridge